services:
  api:
    container_name: fastfoodapi
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile
    networks:
      - fastfood_network
    depends_on:
      - postgres
    ports:
      - "62922:8080"

  postgres:
    image: postgres:16.4-bullseye
    hostname: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fastfood
    networks:
      - fastfood_network
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data 
 
  adminer:
    image: adminer
    hostname: adminer
    container_name: adminer
    restart: always
    ports:
      - 9090:8080
    networks:
      - fastfood_network 
    depends_on:
      - postgres 

volumes:
  pgdata:
  
networks:
  fastfood_network:
    driver: bridge
