version: '3.9'

volumes:
  db_fastfood_data:
networks:
  fast-food-net:
    external: false

services:
  db-fastfood:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_fastfood_data:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - fast-food-net
  fastfood:
    build: .
    ports:
      - "8180:8080"
    depends_on:
      - db-fastfood
    networks:
      - fast-food-net