apiVersion: v1
kind: Service
metadata:
  name: fastfoodapi-service
  labels:
    run: fastfoodapi-service
spec:
  selector:
    app: fastfoodapi-pod
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: NodePort
