name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar dependências de sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y

      - name: Configurar Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Atualizar pip e instalar dependências Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Copy .env.example to .env
        run: cp .env.example .env

      # - name: Executar testes com pytest
      #   run: |
      #     pytest --cov=app --cov-report=xml app/tests/

      # - name: Upload coverage report
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: coverage-report
      #     path: coverage.xml